### ISSUE TITLE
more than one fake node triggers index exception

### ISSUE THREAD

**Issue by trapier** [CumulusNetworks/topology_converter#20]
Adding more than one fake nodes to `examples/2switch_1server.dot` results in the following traceback:
```
Traceback (most recent call last):
  File "topology_converter.py", line 703, in <module>
    main()
  File "topology_converter.py", line 692, in main
    devices=populate_data_structures(inventory)
  File "topology_converter.py", line 582, in populate_data_structures
    return clean_datastructure(devices)
  File "topology_converter.py", line 527, in clean_datastructure
    for index in indexes_to_remove: del devices[index]
IndexError: list assignment index out of range
```

Dot file that produced this.
```
graph dc1 {
 "leaf1" [function="leaf" config="./helper_scripts/extra_switch_config.sh"]
 "leaf2" [function="leaf" config="./helper_scripts/extra_switch_config.sh"]
 "server1" [function="host" config="./helper_scripts/extra_server_config.sh"]
 "server2" [function="fake"]
 "server3" [function="fake"]
   "leaf1":"swp40" -- "leaf2":"swp40"
   "leaf1":"swp50" -- "leaf2":"swp50"
   "server1":"eth1" -- "leaf1":"swp1"
   "server1":"eth2" -- "leaf2":"swp1"
}
```

Fix:

```
diff --git a/topology_converter.py b/topology_converter.py
index 9180fcf..15af414 100755
--- a/topology_converter.py
+++ b/topology_converter.py
@@ -520,7 +520,7 @@ def clean_datastructure(devices):
 
     #Remove Fake Devices
     indexes_to_remove=[]
-    for i in range(0,len(devices)):
+    for i in range(0,len(devices)-1):
         if 'function' in devices[i]:
             if devices[i]['function'] == 'fake':
                 indexes_to_remove.append(i)
```

Will PR shortly.

**Comment by ericpulvino** [comment]
Merged fix in #25
