### ISSUE TITLE
Topology dot file should be linted prior to parsing

### ISSUE THREAD

**Issue by rdarbha** [CumulusNetworks/topology_converter#44]
The topology file currently is not linted, so when the topology_converter.py prints an error, it is very difficult to find the syntax error as the stack trace only points to the code line errors, not the error line in the .dot file.

For example, the following error line:
`101:  "dc1-r101-leaf01":"swp50" --- "dc1-r102-leaf01":"swp16s1"`

Prints the following stack trace:
```
$ python topology_converter.py test.dot --provider=libvirt -s 12000 -g 1000

######################################
          Topology Converter
######################################
           originally written by Eric Pulvino
Traceback (most recent call last):
  File "topology_converter.py", line 760, in <module>
    main()
  File "topology_converter.py", line 747, in main
    inventory = parse_topology(topology_file)
  File "topology_converter.py", line 153, in parse_topology
    topology = pydotplus.graphviz.graph_from_dot_file(topology_file)
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pydotplus/graphviz.py", line 317, in graph_from_dot_file
    return graph_from_dot_data(data)
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pydotplus/graphviz.py", line 302, in graph_from_dot_data
    return parser.parse_dot_data(data)
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pydotplus/parser.py", line 558, in parse_dot_data
    tokens = graphparser.parseString(data)
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3829, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3964, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3698, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3839, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3359, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 3511, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "/Users/rama/VirtualEnv/lib/python2.7/site-packages/pydotplus/parser.py", line 376, in push_node_stmt
    n = pydotplus.Node(str(node_name), **attrs)
TypeError: type object argument after ** must be a mapping, not str

```

**Comment by ericpulvino** [comment]
Fixed in Commit above. Great suggestion!
